[package]
name = "ferrousgl2"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.30"
glutin = "0.32"
glutin-winit = "0.5"
gl = "0.14"
raw-window-handle = "0.6"
glam = "0.30.8"

noise = "0.9.0"